// <auto-generated />
using BugTracker.Main.Features.Backlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BugTracker.Main.Features.Backlog.Data.Migrations
{
    [DbContext(typeof(BacklogDbContext))]
    [Migration("20240808103723_FixNotAutoId")]
    partial class FixNotAutoId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BugTracker.Main.Features.Backlog.ProductBacklogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_product_backlog_item");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_product_backlog_item_project_id");

                    b.ToTable("product_backlog_item", "backlog");
                });

            modelBuilder.Entity("BugTracker.Main.Features.Backlog.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_key");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("OwnerKey", "Key")
                        .HasDatabaseName("ix_project_owner_key_key");

                    b.ToTable("project", "backlog");
                });

            modelBuilder.Entity("BugTracker.Main.Features.Backlog.ProductBacklogItem", b =>
                {
                    b.HasOne("BugTracker.Main.Features.Backlog.Project", "Project")
                        .WithMany("BacklogItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_backlog_item_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BugTracker.Main.Features.Backlog.Project", b =>
                {
                    b.Navigation("BacklogItems");
                });
#pragma warning restore 612, 618
        }
    }
}
